// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(CursoEfContext))]
    [Migration("20250212043224_50UsersSeed")]
    partial class _50UsersSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApplication1.Data.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("users");

                    b.HasData(
                        new
                        {
                            Id = 25,
                            Email = "user25@gmail.com",
                            Password = "123",
                            UserName = "user25"
                        },
                        new
                        {
                            Id = 26,
                            Email = "user26@gmail.com",
                            Password = "123",
                            UserName = "user26"
                        },
                        new
                        {
                            Id = 27,
                            Email = "user27@gmail.com",
                            Password = "123",
                            UserName = "user27"
                        },
                        new
                        {
                            Id = 28,
                            Email = "user28@gmail.com",
                            Password = "123",
                            UserName = "user28"
                        },
                        new
                        {
                            Id = 29,
                            Email = "user29@gmail.com",
                            Password = "123",
                            UserName = "user29"
                        },
                        new
                        {
                            Id = 30,
                            Email = "user30@gmail.com",
                            Password = "123",
                            UserName = "user30"
                        },
                        new
                        {
                            Id = 31,
                            Email = "user31@gmail.com",
                            Password = "123",
                            UserName = "user31"
                        },
                        new
                        {
                            Id = 32,
                            Email = "user32@gmail.com",
                            Password = "123",
                            UserName = "user32"
                        },
                        new
                        {
                            Id = 33,
                            Email = "user33@gmail.com",
                            Password = "123",
                            UserName = "user33"
                        },
                        new
                        {
                            Id = 34,
                            Email = "user34@gmail.com",
                            Password = "123",
                            UserName = "user34"
                        },
                        new
                        {
                            Id = 35,
                            Email = "user35@gmail.com",
                            Password = "123",
                            UserName = "user35"
                        },
                        new
                        {
                            Id = 36,
                            Email = "user36@gmail.com",
                            Password = "123",
                            UserName = "user36"
                        },
                        new
                        {
                            Id = 37,
                            Email = "user37@gmail.com",
                            Password = "123",
                            UserName = "user37"
                        },
                        new
                        {
                            Id = 38,
                            Email = "user38@gmail.com",
                            Password = "123",
                            UserName = "user38"
                        },
                        new
                        {
                            Id = 39,
                            Email = "user39@gmail.com",
                            Password = "123",
                            UserName = "user39"
                        },
                        new
                        {
                            Id = 40,
                            Email = "user40@gmail.com",
                            Password = "123",
                            UserName = "user40"
                        },
                        new
                        {
                            Id = 41,
                            Email = "user41@gmail.com",
                            Password = "123",
                            UserName = "user41"
                        },
                        new
                        {
                            Id = 42,
                            Email = "user42@gmail.com",
                            Password = "123",
                            UserName = "user42"
                        },
                        new
                        {
                            Id = 43,
                            Email = "user43@gmail.com",
                            Password = "123",
                            UserName = "user43"
                        },
                        new
                        {
                            Id = 44,
                            Email = "user44@gmail.com",
                            Password = "123",
                            UserName = "user44"
                        },
                        new
                        {
                            Id = 45,
                            Email = "user45@gmail.com",
                            Password = "123",
                            UserName = "user45"
                        },
                        new
                        {
                            Id = 46,
                            Email = "user46@gmail.com",
                            Password = "123",
                            UserName = "user46"
                        },
                        new
                        {
                            Id = 47,
                            Email = "user47@gmail.com",
                            Password = "123",
                            UserName = "user47"
                        },
                        new
                        {
                            Id = 48,
                            Email = "user48@gmail.com",
                            Password = "123",
                            UserName = "user48"
                        },
                        new
                        {
                            Id = 49,
                            Email = "user49@gmail.com",
                            Password = "123",
                            UserName = "user49"
                        },
                        new
                        {
                            Id = 50,
                            Email = "user50@gmail.com",
                            Password = "123",
                            UserName = "user50"
                        },
                        new
                        {
                            Id = 51,
                            Email = "user51@gmail.com",
                            Password = "123",
                            UserName = "user51"
                        },
                        new
                        {
                            Id = 52,
                            Email = "user52@gmail.com",
                            Password = "123",
                            UserName = "user52"
                        },
                        new
                        {
                            Id = 53,
                            Email = "user53@gmail.com",
                            Password = "123",
                            UserName = "user53"
                        },
                        new
                        {
                            Id = 54,
                            Email = "user54@gmail.com",
                            Password = "123",
                            UserName = "user54"
                        },
                        new
                        {
                            Id = 55,
                            Email = "user55@gmail.com",
                            Password = "123",
                            UserName = "user55"
                        },
                        new
                        {
                            Id = 56,
                            Email = "user56@gmail.com",
                            Password = "123",
                            UserName = "user56"
                        },
                        new
                        {
                            Id = 57,
                            Email = "user57@gmail.com",
                            Password = "123",
                            UserName = "user57"
                        },
                        new
                        {
                            Id = 58,
                            Email = "user58@gmail.com",
                            Password = "123",
                            UserName = "user58"
                        },
                        new
                        {
                            Id = 59,
                            Email = "user59@gmail.com",
                            Password = "123",
                            UserName = "user59"
                        },
                        new
                        {
                            Id = 60,
                            Email = "user60@gmail.com",
                            Password = "123",
                            UserName = "user60"
                        },
                        new
                        {
                            Id = 61,
                            Email = "user61@gmail.com",
                            Password = "123",
                            UserName = "user61"
                        },
                        new
                        {
                            Id = 62,
                            Email = "user62@gmail.com",
                            Password = "123",
                            UserName = "user62"
                        },
                        new
                        {
                            Id = 63,
                            Email = "user63@gmail.com",
                            Password = "123",
                            UserName = "user63"
                        },
                        new
                        {
                            Id = 64,
                            Email = "user64@gmail.com",
                            Password = "123",
                            UserName = "user64"
                        },
                        new
                        {
                            Id = 65,
                            Email = "user65@gmail.com",
                            Password = "123",
                            UserName = "user65"
                        },
                        new
                        {
                            Id = 66,
                            Email = "user66@gmail.com",
                            Password = "123",
                            UserName = "user66"
                        },
                        new
                        {
                            Id = 67,
                            Email = "user67@gmail.com",
                            Password = "123",
                            UserName = "user67"
                        },
                        new
                        {
                            Id = 68,
                            Email = "user68@gmail.com",
                            Password = "123",
                            UserName = "user68"
                        },
                        new
                        {
                            Id = 69,
                            Email = "user69@gmail.com",
                            Password = "123",
                            UserName = "user69"
                        },
                        new
                        {
                            Id = 70,
                            Email = "user70@gmail.com",
                            Password = "123",
                            UserName = "user70"
                        },
                        new
                        {
                            Id = 71,
                            Email = "user71@gmail.com",
                            Password = "123",
                            UserName = "user71"
                        },
                        new
                        {
                            Id = 72,
                            Email = "user72@gmail.com",
                            Password = "123",
                            UserName = "user72"
                        },
                        new
                        {
                            Id = 73,
                            Email = "user73@gmail.com",
                            Password = "123",
                            UserName = "user73"
                        },
                        new
                        {
                            Id = 74,
                            Email = "user74@gmail.com",
                            Password = "123",
                            UserName = "user74"
                        },
                        new
                        {
                            Id = 75,
                            Email = "user75@gmail.com",
                            Password = "123",
                            UserName = "user75"
                        },
                        new
                        {
                            Id = 76,
                            Email = "user76@gmail.com",
                            Password = "123",
                            UserName = "user76"
                        },
                        new
                        {
                            Id = 77,
                            Email = "user77@gmail.com",
                            Password = "123",
                            UserName = "user77"
                        },
                        new
                        {
                            Id = 78,
                            Email = "user78@gmail.com",
                            Password = "123",
                            UserName = "user78"
                        },
                        new
                        {
                            Id = 79,
                            Email = "user79@gmail.com",
                            Password = "123",
                            UserName = "user79"
                        },
                        new
                        {
                            Id = 80,
                            Email = "user80@gmail.com",
                            Password = "123",
                            UserName = "user80"
                        },
                        new
                        {
                            Id = 81,
                            Email = "user81@gmail.com",
                            Password = "123",
                            UserName = "user81"
                        },
                        new
                        {
                            Id = 82,
                            Email = "user82@gmail.com",
                            Password = "123",
                            UserName = "user82"
                        },
                        new
                        {
                            Id = 83,
                            Email = "user83@gmail.com",
                            Password = "123",
                            UserName = "user83"
                        },
                        new
                        {
                            Id = 84,
                            Email = "user84@gmail.com",
                            Password = "123",
                            UserName = "user84"
                        },
                        new
                        {
                            Id = 85,
                            Email = "user85@gmail.com",
                            Password = "123",
                            UserName = "user85"
                        },
                        new
                        {
                            Id = 86,
                            Email = "user86@gmail.com",
                            Password = "123",
                            UserName = "user86"
                        },
                        new
                        {
                            Id = 87,
                            Email = "user87@gmail.com",
                            Password = "123",
                            UserName = "user87"
                        },
                        new
                        {
                            Id = 88,
                            Email = "user88@gmail.com",
                            Password = "123",
                            UserName = "user88"
                        },
                        new
                        {
                            Id = 89,
                            Email = "user89@gmail.com",
                            Password = "123",
                            UserName = "user89"
                        },
                        new
                        {
                            Id = 90,
                            Email = "user90@gmail.com",
                            Password = "123",
                            UserName = "user90"
                        },
                        new
                        {
                            Id = 91,
                            Email = "user91@gmail.com",
                            Password = "123",
                            UserName = "user91"
                        },
                        new
                        {
                            Id = 92,
                            Email = "user92@gmail.com",
                            Password = "123",
                            UserName = "user92"
                        },
                        new
                        {
                            Id = 93,
                            Email = "user93@gmail.com",
                            Password = "123",
                            UserName = "user93"
                        },
                        new
                        {
                            Id = 94,
                            Email = "user94@gmail.com",
                            Password = "123",
                            UserName = "user94"
                        },
                        new
                        {
                            Id = 95,
                            Email = "user95@gmail.com",
                            Password = "123",
                            UserName = "user95"
                        },
                        new
                        {
                            Id = 96,
                            Email = "user96@gmail.com",
                            Password = "123",
                            UserName = "user96"
                        },
                        new
                        {
                            Id = 97,
                            Email = "user97@gmail.com",
                            Password = "123",
                            UserName = "user97"
                        },
                        new
                        {
                            Id = 98,
                            Email = "user98@gmail.com",
                            Password = "123",
                            UserName = "user98"
                        },
                        new
                        {
                            Id = 99,
                            Email = "user99@gmail.com",
                            Password = "123",
                            UserName = "user99"
                        });
                });

            modelBuilder.Entity("WebApplication1.Data.Entities.WorkingExperience", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Environment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("workingExperiences");
                });

            modelBuilder.Entity("WebApplication1.Data.Entities.WorkingExperience", b =>
                {
                    b.HasOne("WebApplication1.Data.Entities.User", "User")
                        .WithMany("WorkingExperiences")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("WebApplication1.Data.Entities.User", b =>
                {
                    b.Navigation("WorkingExperiences");
                });
#pragma warning restore 612, 618
        }
    }
}
